<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Pokemon EDA - Exploratory Data Analysis</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="custom.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Homekachu</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="eda.html">Exploratory Data Analysis</a>
</li>
<li>
  <a href="analysis.html">ML &amp; Statistical Analysis</a>
</li>
<li>
  <a href="rating.html">Rating System</a>
</li>
<li>
  <a href="shiny.html">Interactive Explorer</a>
</li>
<li>
  <a href="https://github.com/PineappleEater/P8105---Final-Project-Pokemon/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="team.html">
    <span class="fa fa-regular fa-address-card"></span>
     
  </a>
</li>
<li>
  <a href="https://www.youtube.com/watch?v=8SJSS_CB6jE">
    <span class="fa fa-brands fa-youtube"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Pokemon EDA - Exploratory Data
Analysis</h1>

</div>


<pre class="r"><code>library(tidyverse)
library(ggplot2)
library(knitr)
library(fmsb)

# Set ggplot theme
theme_set(theme_minimal(base_size = 12))

# Check for optional packages
has_corrplot &lt;- requireNamespace(&quot;corrplot&quot;, quietly = TRUE)
has_patchwork &lt;- requireNamespace(&quot;patchwork&quot;, quietly = TRUE)
has_kableExtra &lt;- requireNamespace(&quot;kableExtra&quot;, quietly = TRUE)

if (has_patchwork) library(patchwork)</code></pre>
<div id="overview" class="section level1">
<h1>Overview</h1>
<div style="text-align: center; margin: 20px 0;">
<p><img src="assets/sprites/gif/wishiwashi-solo-form.gif" width="40" alt="Wishiwashi-solo-form" style="margin: 0 8px;">
<img src="assets/sprites/gif/alcremie.gif" width="40" alt="Alcremie" style="margin: 0 8px;">
<img src="assets/sprites/gif/cinccino.gif" width="70" alt="Cinccino" style="margin: 0 8px;">
<img src="assets/sprites/gif/sprigatito.gif" width="40" alt="Sprigatito" style="margin: 0 8px;">
<img src="assets/sprites/gif/pheromosa.gif" width="70" alt="Pheromosa" style="margin: 0 8px;">
<img src="assets/sprites/gif/gardevoir-mega-gardevoir.gif" width="70" alt="Mega-Gardevoir" style="margin: 0 8px;">
<img src="assets/sprites/gif/diancie-mega-diancie.gif" width="95" alt="Mega-Diancie" style="margin: 0 8px;">
<img src="assets/sprites/gif/rayquaza-mega-rayquaza.gif" width="95" alt="Mega-Rayquaza" style="margin: 0 8px;"></p>
</div>
<p>This page shows a cozy little collection of visualizations for all
major <strong>Pokémon stats</strong> — including the <strong>six base
stats (BST)</strong> of <strong>fully-evolved Pokémon</strong> from all
nine generations, plus their <strong>height</strong>,
<strong>weight</strong>, and <strong>BMI</strong>。</p>
</div>
<div id="stats-analysis" class="section level1">
<h1>Stats Analysis</h1>
<div
style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 20px; margin: 30px 0;">
<div
style="padding: 20px; background: linear-gradient(135deg, #F7D44A 0%, #2cd95c 50%, #F7D44A 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
175 - 780
</div>
<div>
Pokémon Base Stat Total
</div>
<div>
Mean: 519.42
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
1 - 255
</div>
<div>
Pokémon Hit Points
</div>
<div>
Mean: 82.49
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #f5576c 0%, #f093fb 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
10 - 190
</div>
<div>
Attack
</div>
<div>
Mean: 95.85
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
10 - 230
</div>
<div>
Defense
</div>
<div>
Mean: 87.16
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #f76b1c 0%, #fcb045 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
10 - 194
</div>
<div>
Special Attack
</div>
<div>
Mean: 87.19
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
20 - 230
</div>
<div>
Special Defense
</div>
<div>
Mean: 85.36
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #fceabb 0%, #f8b500 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
5 - 200
</div>
<div>
Speed
</div>
<div>
Mean: 81.37
</div>
</div>
</div>
<hr />
<div id="base-stat-total-distribution" class="section level2">
<h2>Base Stat Total Distribution</h2>
<pre class="r"><code># Overall distribution
p1 &lt;- ggplot(pokemon_df, aes(x = total)) +
  geom_histogram(bins = 40, fill = &quot;steelblue&quot;, alpha = 0.7) +
  geom_vline(aes(xintercept = mean(total, na.rm = TRUE)),
    color = &quot;red&quot;, linetype = &quot;dashed&quot;, size = 1
  ) +
  labs(
    title = &quot;Distribution of Base Stat Total (BST)&quot;,
    subtitle = paste(&quot;Mean:&quot;, round(mean(pokemon_df$total, na.rm = TRUE), 1)),
    x = &quot;Total BST&quot;, y = &quot;Count&quot;
  )</code></pre>
<pre class="r"><code>p2 &lt;- ggplot(pokemon_df, aes(x = total, fill = category)) +
  geom_density(alpha = 0.5) +
  scale_fill_brewer(palette = &quot;Set2&quot;) +
  labs(
    title = &quot;BST Distribution by Category&quot;,
    x = &quot;Total BST&quot;, y = &quot;Density&quot;, fill = &quot;Category&quot;
  )

if (has_patchwork) {
  p1 / p2
} else {
  print(p1)
  print(p2)
}</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-1-1.png" width="960" /></p>
<p><strong>Finding</strong>: BST shows a multi-modal distribution with
noticeable right skewness,<br />
indicating structured stat tiers rather than a continuous normal
process.</p>
<p>This becomes more apparent in the “BST Distribution by Category”
visualization. The Base Stat Totals of non-regular Pokémon cluster
tightly around specific values, reflecting the intentional tiering in
Pokémon design.</p>
</div>
<div id="individual-stat-distributions" class="section level2">
<h2>Individual Stat Distributions</h2>
<pre class="r"><code>stat_cols &lt;- c(&quot;hp&quot;, &quot;attack&quot;, &quot;defense&quot;, &quot;sp_atk&quot;, &quot;sp_def&quot;, &quot;speed&quot;)

pokemon_long &lt;- pokemon_df |&gt;
  select(dex, name, category, all_of(stat_cols)) |&gt;
  pivot_longer(
    cols = all_of(stat_cols),
    names_to = &quot;stat&quot;,
    values_to = &quot;value&quot;
  )

ggplot(pokemon_long, aes(x = value, fill = stat)) +
  geom_histogram(bins = 30, alpha = 0.7) +
  facet_wrap(~stat, scales = &quot;free_y&quot;) +
  scale_fill_brewer(palette = &quot;Set3&quot;) +
  labs(
    title = &quot;Distribution of Individual Base Stats&quot;,
    x = &quot;Stat Value&quot;, y = &quot;Count&quot;
  ) +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="eda_files/figure-html/stat-distributions-1.png" width="960" /></p>
<div id="lowest-vs.-highestouter-max-by-mean-of-each-stats"
class="section level3">
<h3>Lowest<img src="assets/sprites/gif/wishiwashi-solo-form.gif" width="40" alt="Wishiwashi-solo-form" style="margin: 0 8px;">
vs. Highest<img src="assets/sprites/gif/rayquaza-mega-rayquaza.gif" width="95" alt="Charizard" style="margin: 0 8px;">(Outer
Max by Mean of each stats)</h3>
<pre class="r"><code>stats_cols &lt;- c(&quot;hp&quot;, &quot;attack&quot;, &quot;defense&quot;, &quot;speed&quot;, &quot;sp_def&quot;, &quot;sp_atk&quot;)

p1 &lt;- pokemon_df |&gt; filter(name == &quot;WishiwashiSolo Form&quot;) |&gt; select(all_of(stats_cols))
p2 &lt;- pokemon_df |&gt; filter(name == &quot;RayquazaMega Rayquaza&quot;) |&gt; select(all_of(stats_cols))

# Set Max
max_row &lt;- pokemon_df |&gt;
  summarise(across(all_of(stats_cols), ~ mean(.x, na.rm = TRUE)))
min_row &lt;- rep(0, length(stats_cols))

radar_data &lt;- rbind(max_row, min_row, p1, p2)
rownames(radar_data) &lt;- c(&quot;Max&quot;, &quot;Min&quot;, &quot;WishiwashiSolo Form&quot;, &quot;RayquazaMega Rayquaza&quot;)

# Plot
radarchart(radar_data,
           axistype = 1,
           pcol = c(&quot;#4FACFE&quot;, &quot;#007F3A&quot;),
           pfcol = adjustcolor(c(&quot;#4FACFE&quot;, &quot;#007F3A&quot;), alpha.f = 0.3),
           plwd = 3,
           plty = 1,
           cglcol = &quot;grey&quot;, 
           cglty = 1,
  )
legend(&quot;topright&quot;, legend = c(&quot;Wishiwashi Solo Form&quot;, &quot;Mega Rayquaza&quot;),
       col = c(&quot;#4FACFE&quot;, &quot;#007F3A&quot;), pch = 19, bty = &quot;n&quot;)</code></pre>
<p><img src="eda_files/figure-html/unnamed-chunk-2-1.png" width="960" /></p>
</div>
</div>
<div id="physical-attributes" class="section level2">
<h2>Physical Attributes</h2>
<div
style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 20px; margin: 30px 0;">
<div
style="padding: 20px; background: linear-gradient(135deg, #a1ffce 0%, #faffd1 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
0.1 - 20
</div>
<div>
Pokémon Height
</div>
<div>
Mean: 1.7
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #6a11cb 0%, #2575fc 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
0.1 - 999.9
</div>
<div>
Pokémon Weight
</div>
<div>
Mean: 106.73
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #e3a1ff 0%, #ffedbc 100%); border-radius: 15px; color: white;">
<div style="font-size: 2em; font-weight: bold;">
0.4 - 644
</div>
<div>
Body Mass Index
</div>
<div>
Mean: 37.24
</div>
</div>
</div>
<hr />
<pre class="r"><code>p1 &lt;- ggplot(pokemon_df, aes(x = height_m)) +
  geom_histogram(bins = 40, fill = &quot;darkgreen&quot;, alpha = 0.7) +
  scale_x_log10() +
  labs(
    title = &quot;Height Distribution (log scale)&quot;,
    x = &quot;Height (m)&quot;, y = &quot;Count&quot;
  )

p2 &lt;- ggplot(pokemon_df, aes(x = weight_kgs)) +
  geom_histogram(bins = 40, fill = &quot;darkorange&quot;, alpha = 0.7) +
  scale_x_log10() +
  labs(
    title = &quot;Weight Distribution (log scale)&quot;,
    x = &quot;Weight (kg)&quot;, y = &quot;Count&quot;
  )

p3 &lt;- pokemon_df |&gt;
  filter(bmi &lt; 1000) |&gt; # Filter extreme outliers (Cosmoem BMI=99990)
  # otherwise the plot will be severly compressed
  ggplot(aes(x = bmi)) +
  geom_histogram(bins = 40, fill = &quot;purple&quot;, alpha = 0.7) +
  labs(
    title = &quot;BMI Distribution (filtered &lt; 1000)&quot;,
    subtitle = &quot;Note: Cosmoem (BMI=99,990) excluded as extreme outlier&quot;,
    x = &quot;BMI&quot;, y = &quot;Count&quot;
  )

if (has_patchwork) {
  (p1 | p2) / p3
} else {
  print(p1)
  print(p2)
  print(p3)
}</code></pre>
<p><img src="eda_files/figure-html/physical-dist-1.png" width="960" /></p>
<div id="weight-vs.-height" class="section level3">
<h3>Weight vs. Height</h3>
<pre class="r"><code>ggplot(pokemon_df, aes(x = height_m, y = weight_kgs, color = type_1)) +
  geom_point(alpha = 0.6, size = 2) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = &quot;lm&quot;, se = FALSE, color = &quot;black&quot;) +
  labs(
    title = &quot;Height vs Weight (log-log scale)&quot;,
    x = &quot;Height (m)&quot;, y = &quot;Weight (kg)&quot;, color = &quot;Primary Type&quot;
  ) +
  theme(legend.position = &quot;right&quot;)</code></pre>
<p><img src="eda_files/figure-html/height-weight-1.png" width="960" /></p>
</div>
</div>
</div>
<div id="type-analysis" class="section level1">
<h1>Type Analysis</h1>
<div
style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 20px; margin: 30px 0;">
<div
style="padding: 20px; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
18
</div>
<div>
Total Different Types
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
171
</div>
<div>
Total Type Combination(Includ Mono-type)
</div>
</div>
</div>
<hr />
<div id="type-distribution" class="section level2">
<h2>Type Distribution</h2>
<pre class="r"><code># Official Type Color
type_colors &lt;- c(
  Normal   = &quot;#A8A77A&quot;,
  Fire     = &quot;#EE8130&quot;,
  Water    = &quot;#6390F0&quot;,
  Electric = &quot;#F7D02C&quot;,
  Grass    = &quot;#7AC74C&quot;,
  Ice      = &quot;#96D9D6&quot;,
  Fighting = &quot;#C22E28&quot;,
  Poison   = &quot;#A33EA1&quot;,
  Ground   = &quot;#E2BF65&quot;,
  Flying   = &quot;#A98FF3&quot;,
  Psychic  = &quot;#F95587&quot;,
  Bug      = &quot;#A6B91A&quot;,
  Rock     = &quot;#B6A136&quot;,
  Ghost    = &quot;#735797&quot;,
  Dragon   = &quot;#6F35FC&quot;,
  Dark     = &quot;#705746&quot;,
  Steel    = &quot;#B7B7CE&quot;,
  Fairy    = &quot;#D685AD&quot;
)

# Types(Normal+Fly will both count to Normal and Flying type)
p1 &lt;- pokemon_df |&gt;
  pivot_longer(
    cols = c(type_1, type_2),
    names_to = &quot;slot&quot;,
    values_to = &quot;type&quot;
  ) |&gt;
  filter(!is.na(type)) |&gt;
  count(type, sort = TRUE) |&gt;
  head(10) |&gt;
  ggplot(aes(x = reorder(type, n), y = n, fill = type)) +
  geom_col(alpha = 0.8) +
  scale_fill_manual(values = type_colors) +
  coord_flip() +
  labs(title = &quot;Top 10 Types&quot;, x = &quot;Type&quot;, y = &quot;Count&quot;) +
  theme(legend.position = &quot;none&quot;)

# Dual-type proportion
p2 &lt;- pokemon_df |&gt;
  count(is_dual_type) |&gt;
  mutate(label = if_else(is_dual_type, &quot;Dual-type&quot;, &quot;Mono-type&quot;)) |&gt;
  ggplot(aes(x = &quot;&quot;, y = n, fill = label)) +
  geom_col(width = 1) +
  coord_polar(&quot;y&quot;) +
  labs(title = &quot;Mono-type vs Dual-type&quot;, fill = &quot;&quot;) +
  theme_void()

if (has_patchwork) {
  p1 | p2
} else {
  print(p1)
  print(p2)
}</code></pre>
<p><img src="eda_files/figure-html/type-counts-1.png" width="960" /></p>
<div id="type-combinations" class="section level3">
<h3>Type Combinations</h3>
<pre class="r"><code># Top type combinations
pokemon_df |&gt;
  filter(!is.na(type_2)) |&gt;
  count(type_1, type_2, sort = TRUE) |&gt;
  head(15) |&gt;
  mutate(combo = paste(type_1, &quot;/&quot;, type_2)) |&gt;
  ggplot(aes(x = reorder(combo, n), y = n, fill = type_1)) +
  geom_col(alpha = 0.8) +
  scale_fill_manual(values = type_colors) +
  coord_flip() +
  labs(
    title = &quot;Top 15 Type Combinations&quot;,
    x = &quot;Type Combination&quot;, y = &quot;Count&quot;, fill = &quot;Primary Type&quot;
  )</code></pre>
<p><img src="eda_files/figure-html/type-combos-1.png" width="960" /></p>
</div>
</div>
<div id="stats-by-type" class="section level2">
<h2>Stats by Type</h2>
<pre class="r"><code># Get types ranking
top_types &lt;- pokemon_df |&gt;
  pivot_longer(
    cols = c(type_1, type_2),
    names_to = &quot;slot&quot;,
    values_to = &quot;type&quot;
  ) |&gt;
  filter(!is.na(type)) |&gt;
  count(type, sort = TRUE) |&gt;
  pull(type)

pokemon_df |&gt;
  filter(type_1 %in% top_types) |&gt;
  ggplot(aes(x = reorder(type_1, total, median), y = total, fill = type_1)) +
  geom_boxplot(alpha = 0.7) +
  scale_fill_manual(values = type_colors) +
  coord_flip() +
  labs(
    title = &quot;BST by Type(Most mean to least)&quot;,
    x = &quot;Owned Type&quot;, y = &quot;Total BST&quot;
  ) +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="eda_files/figure-html/stats-by-type-1.png" width="960" /></p>
<div id="average-stats-by-type" class="section level3">
<h3>Average Stats by Type</h3>
<pre class="r"><code># Calculate average stats per type
type_stats &lt;- pokemon_df |&gt;
  pivot_longer(
    cols = c(type_1, type_2),
    names_to = &quot;slot&quot;,
    values_to = &quot;type&quot;
  ) |&gt;
  filter(!is.na(type)) |&gt;
  group_by(type) |&gt;
  summarise(
    count = n(),
    avg_total = mean(total, na.rm = TRUE),
    avg_hp = mean(hp, na.rm = TRUE),
    avg_attack = mean(attack, na.rm = TRUE),
    avg_sp_atk = mean(sp_atk, na.rm = TRUE),
    avg_defense = mean(defense, na.rm = TRUE),
    avg_sp_def = mean(sp_def, na.rm = TRUE),
    avg_speed = mean(speed, na.rm = TRUE)
  ) |&gt;
  arrange(desc(avg_total))

# Heatmap
type_stats |&gt;
  select(type, avg_hp, avg_attack, avg_sp_atk, avg_defense, avg_sp_def, avg_speed) |&gt;
  pivot_longer(-type, names_to = &quot;stat&quot;, values_to = &quot;value&quot;) |&gt;
  mutate(stat = str_remove(stat, &quot;avg_&quot;)) |&gt;
  ggplot(aes(x = stat, y = reorder(type, value), fill = value)) +
  geom_tile() +
  scale_fill_gradientn(
    colours = c(&quot;#b9d6f2&quot;, &quot;#d0e1f9&quot;, &quot;#f7f9ff&quot;, &quot;#f9d5e5&quot;, &quot;#f6b0c3&quot;),
    name = &quot;Average Value&quot;
  ) +
  labs(
    title = &quot;Average Stats Heatmap (Top 12 Types by BST)&quot;,
    x = &quot;Stat&quot;, y = &quot;Owned Type&quot;, fill = &quot;Average Value&quot;
  )</code></pre>
<p><img src="eda_files/figure-html/avg-stats-type-1.png" width="960" /></p>
</div>
</div>
</div>
<div id="special-categories-deep-dive" class="section level1">
<h1>Special Categories Deep Dive</h1>
<pre class="r"><code>category_stats &lt;- pokemon_df |&gt;
  group_by(category) |&gt;
  summarise(
    count = n(),
    avg_total = mean(total, na.rm = TRUE),
    avg_hp = mean(hp, na.rm = TRUE),
    avg_attack = mean(attack, na.rm = TRUE),
    avg_defense = mean(defense, na.rm = TRUE),
    avg_sp_atk = mean(sp_atk, na.rm = TRUE),
    avg_sp_def = mean(sp_def, na.rm = TRUE),
    avg_speed = mean(speed, na.rm = TRUE)
  ) |&gt;
  arrange(desc(avg_total))</code></pre>
<div
style="display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 20px; margin: 30px 0;">
<div
style="padding: 20px; background: linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
101
</div>
<div>
Legendary Pokémons
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
28
</div>
<div>
Mythical Pokémons
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #7f7fd5 0%, #86a8e7 50%, #91eae4 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
20
</div>
<div>
Paradox Pokémons
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #f6d365 0%, #fda085 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
10
</div>
<div>
Ultra Beast Pokémons
</div>
</div>
<div
style="padding: 20px; background: linear-gradient(135deg, #a1ffce 0%, #faffd1 100%); border-radius: 15px; color: white;">
<div style="font-size: 2.5em; font-weight: bold;">
583
</div>
<div>
Regular Pokémons
</div>
</div>
</div>
<hr />
<div id="legendary-vs-all-others-stats" class="section level2">
<h2>Legendary vs all Others Stats</h2>
<pre class="r"><code># Statistical test
legendary_test &lt;- t.test(total ~ is_legendary, data = pokemon_df)
legendary_test</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  total by is_legendary
## t = -16.771, df = 129.73, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group FALSE and group TRUE is not equal to 0
## 95 percent confidence interval:
##  -135.2013 -106.6682
## sample estimates:
## mean in group FALSE  mean in group TRUE 
##            502.9563            623.8911</code></pre>
<pre class="r"><code># Violin plot
pokemon_df |&gt;
  mutate(label = if_else(is_legendary, &quot;Legendary&quot;, &quot;Others&quot;)) |&gt;
  ggplot(aes(x = label, y = total, fill = label)) +
  geom_violin(alpha = 0.7) +
  geom_boxplot(width = 0.2, alpha = 0.5) +
  scale_fill_manual(values = c(&quot;Others&quot; = &quot;steelblue&quot;, &quot;Legendary&quot; = &quot;gold&quot;)) +
  labs(
    title = &quot;BST: Legendary vs Other Pokemons&quot;,
    x = &quot;&quot;, y = &quot;Total BST&quot;
  ) +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="eda_files/figure-html/legendary-comparison-1.png" width="960" /></p>
<p><strong>Finding</strong>: Based on a Welch two-sample t-test (t =
-16.77, p &lt; 2.8^{-34}), Legendary Pokémon have a significantly higher
mean BST (623.9) compared to non-Legendary Pokémon (503).</p>
<p><em>The Violin plot gives same result</em>: Legendary Pokémon have
significantly higher and more concentrated total base stats compared to
all other Pokémon, whose BST values are far more diverse and widely
spread.</p>
</div>
<div id="all-special-categories" class="section level2">
<h2>All Special Categories</h2>
<pre class="r"><code>kable(category_stats, caption = &quot;Average Stats by Category&quot;, digits = 1)</code></pre>
<table>
<caption>Average Stats by Category</caption>
<colgroup>
<col width="13%" />
<col width="6%" />
<col width="11%" />
<col width="7%" />
<col width="12%" />
<col width="13%" />
<col width="12%" />
<col width="12%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">category</th>
<th align="right">count</th>
<th align="right">avg_total</th>
<th align="right">avg_hp</th>
<th align="right">avg_attack</th>
<th align="right">avg_defense</th>
<th align="right">avg_sp_atk</th>
<th align="right">avg_sp_def</th>
<th align="right">avg_speed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Legendary</td>
<td align="right">101</td>
<td align="right">623.9</td>
<td align="right">98.3</td>
<td align="right">112.6</td>
<td align="right">99.4</td>
<td align="right">111.0</td>
<td align="right">103.4</td>
<td align="right">99.3</td>
</tr>
<tr class="even">
<td align="left">Mythical</td>
<td align="right">28</td>
<td align="right">601.4</td>
<td align="right">83.9</td>
<td align="right">109.3</td>
<td align="right">98.5</td>
<td align="right">111.9</td>
<td align="right">96.2</td>
<td align="right">101.6</td>
</tr>
<tr class="odd">
<td align="left">Paradox</td>
<td align="right">20</td>
<td align="right">578.0</td>
<td align="right">95.9</td>
<td align="right">103.6</td>
<td align="right">94.5</td>
<td align="right">93.9</td>
<td align="right">90.7</td>
<td align="right">99.4</td>
</tr>
<tr class="even">
<td align="left">Ultra Beast</td>
<td align="right">10</td>
<td align="right">567.0</td>
<td align="right">93.6</td>
<td align="right">113.2</td>
<td align="right">91.8</td>
<td align="right">108.4</td>
<td align="right">73.0</td>
<td align="right">87.0</td>
</tr>
<tr class="odd">
<td align="left">Regular</td>
<td align="right">583</td>
<td align="right">494.6</td>
<td align="right">79.0</td>
<td align="right">91.7</td>
<td align="right">84.2</td>
<td align="right">81.3</td>
<td align="right">81.8</td>
<td align="right">76.6</td>
</tr>
</tbody>
</table>
</div>
<div id="key-findings-summary" class="section level2">
<h2>9. Key Findings Summary</h2>
<pre class="r"><code>library(glue)

cat(glue(&quot;=== EDA KEY FINDINGS ===

1. Dataset Overview:
   - Total Pokemon: {nrow(pokemon_df)}
   - Legendary: {sum(pokemon_df$is_legendary)}
   - Mythical: {sum(pokemon_df$is_mythical)}
   - Regular: {sum(!pokemon_df$is_special)}

2. Base Stats:
   - Mean BST: {round(mean(pokemon_df$total, na.rm = TRUE), 1)}
   - BST Range: {min(pokemon_df$total, na.rm = TRUE)} - {max(pokemon_df$total, na.rm = TRUE)}

3. Type Distribution:
   - Unique primary types: {length(unique(pokemon_df$type_1))}
   - Dual-type Pokemon: {sum(pokemon_df$is_dual_type)} ({round(100 * mean(pokemon_df$is_dual_type), 1)}%)

4. Statistical Tests:
   - Legendary vs Regular BST p-value: {format(legendary_test$p.value, scientific = TRUE, digits = 3)}
   - Difference is {if_else(legendary_test$p.value &lt; 0.001, &#39;highly&#39;, &#39;&#39;)} significant

5. Correlations:
   - Total vs Attack: {round(cor(pokemon_df$total, pokemon_df$attack, use = &#39;complete.obs&#39;), 3)}
   - Attack vs Defense: {round(cor(pokemon_df$attack, pokemon_df$defense, use = &#39;complete.obs&#39;), 3)}
   - Height vs Weight: {round(cor(pokemon_df$height_m, pokemon_df$weight_kgs, use = &#39;complete.obs&#39;), 3)}

6. Physical Attributes:
   - BMI Range (excluding outliers): {round(min(pokemon_df$bmi[pokemon_df$bmi &lt; 1000], na.rm = TRUE), 1)} - {round(max(pokemon_df$bmi[pokemon_df$bmi &lt; 1000], na.rm = TRUE), 1)}
   - Extreme outlier: Cosmoem (BMI = 99,990) due to ultra-dense core
   - Height range: {min(pokemon_df$height_m, na.rm = TRUE)} - {max(pokemon_df$height_m, na.rm = TRUE)} m
   - Weight range: {min(pokemon_df$weight_kgs, na.rm = TRUE)} - {max(pokemon_df$weight_kgs, na.rm = TRUE)} kg
&quot;))</code></pre>
<pre><code>## === EDA KEY FINDINGS ===
## 
## 1. Dataset Overview:
##    - Total Pokemon: 742
##    - Legendary: 101
##    - Mythical: 28
##    - Regular: 583
## 
## 2. Base Stats:
##    - Mean BST: 519.4
##    - BST Range: 175 - 780
## 
## 3. Type Distribution:
##    - Unique primary types: 18
##    - Dual-type Pokemon: 471 (63.5%)
## 
## 4. Statistical Tests:
##    - Legendary vs Regular BST p-value: 2.77e-34
##    - Difference is highly significant
## 
## 5. Correlations:
##    - Total vs Attack: 0.545
##    - Attack vs Defense: 0.216
##    - Height vs Weight: 0.631
## 
## 6. Physical Attributes:
##    - BMI Range (excluding outliers): 0.4 - 644
##    - Extreme outlier: Cosmoem (BMI = 99,990) due to ultra-dense core
##    - Height range: 0.1 - 20 m
##    - Weight range: 0.1 - 999.9 kg</code></pre>
<hr />
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
